
post http://localhost:3004/course
content-Type: application/json

{
  "name": "Full Stack Developer",
  "structure": {
    "nodes": [
      {
        "id": "1",
        "position": {
          "x": 0,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "HTML",
          "_id": "665a9d95dc1cb9098f90993c",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "2",
        "position": {
          "x": 100,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "CSS",
          "_id": "665a6060a44e44e2767889a6",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "3",
        "position": {
          "x": 200,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "Java Script",
          "_id": "665a9d51dc1cb9098f90993a",
          "sourcePosition": "Position.Bottom",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "4",
        "position": {
          "x": 200,
          "y": 30
        },
        "type": "customNode",
        "data": {
          "label": "nmp",
          "_id": "666df33cfbf21f5b7328b06f",
          "sourcePosition": "Position.Left",
          "targetPosition": "Position.Top"
        }
      },
      {
        "id": "5",
        "sourcePosition": "left",
        "targetPosition": "right",
        "position": {
          "x": 100,
          "y": 30
        },
        "type": "customNode",
        "data": {
          "label": "Git & GitHub",
          "_id": "666c822ae8ad2e4e5b00112a",
          "sourcePosition": "Position.Left",
          "targetPosition": "Position.Right"
        }
      }, 
      {
        "id": "6",        
        "position": {
          "x": 0,
          "y": 30
        },
        "type": "customNode",
        "data": {
          "label": "React.js",
          "_id": "665a9de8dc1cb9098f90993e",
          "sourcePosition": "Position.Bottom",
          "targetPosition": "Position.Right"
        }
      },
      {
        "id": "7",        
        "position": {
          "x": 0,
          "y": 100
        },
        "type": "customNode",
        "data": {
          "label": "Node.js",
          "_id": "666df3c5fbf21f5b7328b07c",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Top"
        }
      },
      {
        "id": "8",        
        "position": {
          "x": 100,
          "y": 100
        },
        "type": "customNode",
        "data": {
          "label": "PostgreSQL",
          "_id": "666df3fcfbf21f5b7328b07e",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Top"
        }
      },
      {
        "id": "9",        
        "position": {
          "x": 200,
          "y": 100
        },
        "type": "customNode",
        "data": {
          "label": "RESTful API",
          "_id": "666df437fbf21f5b7328b080",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Top"
        }
      },
      {
        "id": "10",        
        "position": {
          "x": 300,
          "y": 100
        },
        "type": "customNode",
        "data": {
          "label": "JWT Auth",
          "_id": "666df473fbf21f5b7328b082",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Top"
        }
      }
      
    ],
    "edges": [
      {
        "id": "e1-2",
        "source": "1",
        "target": "2",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e2-3",
        "source": "2",
        "target": "3",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e3-4",
        "source": "3",
        "target": "4",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e4-5",
        "source": "4",
        "target": "5",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e5-6",
        "source": "5",
        "target": "6",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e6-7",
        "source": "6",
        "target": "7",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e7-8",
        "source": "7",
        "target": "8",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e8-9",
        "source": "8",
        "target": "9",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      },
      {
        "id": "e9-10",
        "source": "9",
        "target": "10",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 7,
          "height": 7,
          "color": "black"
        },
        "style": {
          "strokeWidth": 1,
          "stroke": "black"
        }
      }
    ]
  }
  }


###
get http://localhost:3004/course
content-Type: application/json


###
get http://localhost:3004/course/Front End
content-Type: application/json


###

post http://localhost:3004/user/signup
content-Type: application/json

{
  "username": "jim",
  "email": "jim@gmail.com",
  "password": "passwordjim",
  "aboutMe": "like to sleep"
}


###

post http://localhost:3004/user/lessoncompleted/:id
content-Type: application/json


###

post http://localhost:3004/user/login
content-Type: application/json

{
  "username": "jim",
  "password": "passwordjim"
}


###

post http://localhost:3004/lesson/create
content-Type: application/json

{
  "name": "JWT Auth",
  "desc": "JWT stands for JSON Web Token is a token-based encryption open standard/methodology that is used to transfer information securely as a JSON object. Clients and Servers use JWT to securely share information, with the JWT containing encoded JSON objects and claims. JWT tokens are designed to be compact, safe to use within URLs, and ideal for SSO contexts.",
  "urls": ["https://jwt.io/", "https://www.akana.com/blog/what-is-jwt"],
  "isCompleted": false
}

###

get http://localhost:3004/lesson/665a6060a44e44e2767889a6
content-Type: application/json



    

###

put http://localhost:3004/lesson/checkbox/665a6060a44e44e2767889a6
content-Type: application/json

{
  "isCompleted": "false"
  
}

    



