


post http://localhost:3004/course
content-Type: application/json

{
  "name": "Front End",
  "structure": {
    "nodes": [
      {
        "id": "1",
        "position": {
          "x": 0,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "HTML",
          "_id": "665a44d138f4192b6cb2e5d0",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "2",
        "position": {
          "x": 200,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "CSS",
          "_id": "665a6060a44e44e2767889a6",
          "sourcePosition": "Position.Right",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "3",
        "position": {
          "x": 400,
          "y": -40
        },
        "type": "customNode",
        "data": {
          "label": "Java Script",
          "sourcePosition": "Position.Bottom",
          "targetPosition": "Position.Left"
        }
      },
      {
        "id": "4",
        "position": {
          "x": 400,
          "y": 60
        },
        "type": "customNode",
        "data": {
          "label": "React JS",
          "sourcePosition": "Position.Left",
          "targetPosition": "Position.Top"
        }
      },
      {
        "id": "5",
        "sourcePosition": "left",
        "targetPosition": "right",
        "position": {
          "x": 200,
          "y": 60
        },
        "type": "customNode",
        "data": {
          "label": "Git",
          "sourcePosition": "Position.Left",
          "targetPosition": "Position.Right"
        }
      }
    ],
    "edges": [
      {
        "id": "e1-2",
        "source": "1",
        "target": "2",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 10,
          "height": 10,
          "color": "black"
        },
        "style": {
          "strokeWidth": 2,
          "stroke": "black"
        }
      },
      {
        "id": "e2-3",
        "source": "2",
        "target": "3",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 10,
          "height": 10,
          "color": "black"
        },
        "style": {
          "strokeWidth": 2,
          "stroke": "black"
        }
      },
      {
        "id": "e3-4",
        "source": "3",
        "target": "4",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 10,
          "height": 10,
          "color": "black"
        },
        "style": {
          "strokeWidth": 2,
          "stroke": "black"
        }
      },
      {
        "id": "e4-5",
        "source": "4",
        "target": "5",
        "markerEnd": {
          "type": "MarkerType.ArrowClosed",
          "width": 10,
          "height": 10,
          "color": "black"
        },
        "style": {
          "strokeWidth": 2,
          "stroke": "black"
        }
      }
    ]
  }
  }


###
get http://localhost:3004/course
content-Type: application/json


###
get http://localhost:3004/course/Front End
content-Type: application/json


###

post http://localhost:3004/user/signup
content-Type: application/json

{
  "username": "jim",
  "email": "jim@gmail.com",
  "password": "passwordjim",
  "aboutMe": "like to sleep"
}

###

post http://localhost:3004/user/login
content-Type: application/json

{
  "username": "jim",
  "password": "passwordjim"
}


###

post http://localhost:3004/lesson/create
content-Type: application/json

{
  "name": "CSS",
  "desc": "CSS lorem Ipsum",
  "urls": ["https://www.w3schools.com/css/", "https://developer.mozilla.org/en-US/docs/Web/CSS"],
  "isCompleted": false
}

###

get http://localhost:3004/lesson/665a6060a44e44e2767889a6
content-Type: application/json



    

###

put http://localhost:3004/lesson/checkbox/665a6060a44e44e2767889a6
content-Type: application/json

{
  "isCompleted": "false"
  
}

    



